### PR TITLE
aead: fixing import error

### PR DESCRIPTION
**Pull request by Yayg**
When go building a basic example using aead go was unable to find the
module because it was hidden under a subdirectory.

Typical error message:
```
% go build test.go
go: finding github.com/perlin-network/noise/handshake/ecdh latest
go: finding github.com/perlin-network/noise/skademlia latest
go: finding github.com/perlin-network/noise/identity/ed25519 latest
go: finding github.com/perlin-network/noise/rpc latest
go: finding github.com/perlin-network/noise/cipher/aead latest
go: finding github.com/perlin-network/noise/protocol latest
go: finding github.com/perlin-network/noise/handshake latest
go: finding github.com/perlin-network/noise/identity latest
go: finding github.com/perlin-network/noise/cipher latest
build command-line-arguments: cannot load github.com/perlin-network/noise/cipher/aead: cannot find module providing package github.com/perlin-network/noise/cipher/aead
```

### CODE REVIEW

**Comment by a-urth** [comment]
@Yayg which example you was trying to build exactly?
if it was your example, can you please provide code as well?

**Comment by a-urth** [comment]
Btw, `master` branch is previous/outdated version of noise. Current (future release which already used in `wavelet`) version is in `cleanup` branch.

**Comment by Yayg** [comment]
Hi @a-urth,

I litterally copy pasted the example from the README.md.
I'll try with the cleanup branch.

**Comment by Lisahobe1998** [comment]
Wenn will you release the new noise master branch?

**Pull request closed without merging**
